# Basic PyTorch Commands

In [82]:
import torch


In [83]:
x1 = torch.empty(2, 3)
print(x1)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [84]:
x2 = torch.rand(1, 5)
print(x2)


tensor([[0.1299, 0.2982, 0.4852, 0.4762, 0.5174]])


In [85]:
x3 = torch.ones(3, 4, dtype=torch.int64)
print(x3)


tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


In [86]:
print(x1.size())


torch.Size([2, 3])


In [87]:
x = torch.ones(3, 3)
y = torch.zeros(3, 3)
z = x+y
print(z)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [88]:
y.add_(x)  # matrix addition
print(y)

print(y+1)  # scalar added to every element


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [90]:
x = torch.full((3, 3), 2)
y = torch.full((3, 3), 5)

z1 = x*y  # Not matrix mutliplication but multiplies each element
print(z1)

z2 = torch.mm(x, y)  # Matrix multiplication
print(z2)


tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])
tensor([[30, 30, 30],
        [30, 30, 30],
        [30, 30, 30]])


In [99]:
x = torch.rand(5, 3)
print(x)
print(x[:, 2])
print(x[:1, :2])
print(x[1, 1].item())


tensor([[0.7752, 0.8597, 0.1997],
        [0.1481, 0.1694, 0.1882],
        [0.7611, 0.2670, 0.3894],
        [0.4922, 0.5728, 0.7434],
        [0.1110, 0.3093, 0.2084]])
tensor([0.1997, 0.1882, 0.3894, 0.7434, 0.2084])
tensor([[0.7752, 0.8597]])
0.16938704252243042


In [105]:
x = torch.rand(4, 4)
y1 = x.view(16)
print(y1)

y2 = x.view(-1, 4) # -1 argument means "infer this dimension automatically based on the other dimensions and the total number of elements in the tensor"
print(y2)


tensor([0.1019, 0.4836, 0.7728, 0.3683, 0.6798, 0.0398, 0.6978, 0.9623, 0.0132,
        0.0711, 0.4098, 0.2881, 0.4993, 0.0359, 0.0019, 0.9373])
tensor([[0.1019, 0.4836, 0.7728, 0.3683],
        [0.6798, 0.0398, 0.6978, 0.9623],
        [0.0132, 0.0711, 0.4098, 0.2881],
        [0.4993, 0.0359, 0.0019, 0.9373]])


In [108]:
x = torch.ones(5, requires_grad=True) # If you want to optmize the parameter with gradients
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
